services:
  api:
    build:
      context: ../sargentacao-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8080"
    restart: unless-stopped

  web:
    build:
      context: ../sargentacao-web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped
